<?php

namespace ContainerYF8wxM2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RKLgmBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RK_lgmB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RK_lgmB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'address' => ['privates', '.errored..service_locator.RK_lgmB.App\\Entity\\Address', NULL, 'Cannot autowire service ".service_locator.RK_lgmB": it references class "App\\Entity\\Address" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'address' => 'App\\Entity\\Address',
            'entityManager' => '?',
            'translator' => '?',
        ]);
    }
}
