<?php

namespace ContainerYF8wxM2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RK_lgmB.App\Entity\Address' shared service.
     *
     * @return \App\Entity\Address
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RK_lgmB": it references class "App\\Entity\\Address" but no such service exists.');
    }
}
