<?php

namespace ContainerRrmjxWt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hhm5ig8.App\Entity\Order' shared service.
     *
     * @return \App\Entity\Order
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hhm5ig8": it references class "App\\Entity\\Order" but no such service exists.');
    }
}
