<?php

namespace Container4qLG53j;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NYDqIZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NY_dqIZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NY_dqIZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'category' => ['privates', '.errored..service_locator.NY_dqIZ.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.NY_dqIZ": it references class "App\\Entity\\Category" but no such service exists.'],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'category' => 'App\\Entity\\Category',
            'entityManagerInterface' => '?',
            'paginator' => '?',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
