<?php

namespace ContainerV6dG3kK;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SGVGXxvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SGVGXxv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SGVGXxv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ordersRepository' => ['privates', 'App\\Repository\\OrdersRepository', 'getOrdersRepositoryService', true],
            'stripe' => ['privates', 'App\\Services\\Stripe', 'getStripeService', true],
        ], [
            'entityManagerInterface' => '?',
            'ordersRepository' => 'App\\Repository\\OrdersRepository',
            'stripe' => 'App\\Services\\Stripe',
        ]);
    }
}
