<?php

namespace ContainerV6dG3kK;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3RmaU_PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3RmaU.P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3RmaU.P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'addressRepository' => ['privates', 'App\\Repository\\AddressRepository', 'getAddressRepositoryService', true],
        ], [
            'addressRepository' => 'App\\Repository\\AddressRepository',
        ]);
    }
}
