<?php

namespace ContainerXm8YmtB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U7ZGiuAService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.U7ZGiuA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U7ZGiuA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'produc' => ['privates', '.errored..service_locator.U7ZGiuA.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.U7ZGiuA": it references class "App\\Entity\\Product" but no such service exists.'],
            'translator' => ['services', 'translator', 'getTranslatorService', true],
        ], [
            'entityManager' => '?',
            'paginator' => '?',
            'produc' => 'App\\Entity\\Product',
            'translator' => '?',
        ]);
    }
}
