<?php

namespace ContainerXm8YmtB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeliveryAddressControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DeliveryAddressController' shared autowired service.
     *
     * @return \App\Controller\DeliveryAddressController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DeliveryAddressController'] = $instance = new \App\Controller\DeliveryAddressController(($container->privates['App\\Services\\CartServices'] ?? $container->load('getCartServicesService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\DeliveryAddressController', $container));

        return $instance;
    }
}
