<?php

namespace ContainerXm8YmtB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenderRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\GenderRepository' shared autowired service.
     *
     * @return \App\Repository\GenderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\GenderRepository'] = new \App\Repository\GenderRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
