<?php

namespace ContainerXm8YmtB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewslettersControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\NewslettersController' shared autowired service.
     *
     * @return \App\Controller\NewslettersController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\NewslettersController'] = $instance = new \App\Controller\NewslettersController(($container->services['doctrine'] ?? $container->getDoctrineService()));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\NewslettersController', $container));

        return $instance;
    }
}
