<?php

namespace ContainerXm8YmtB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewslettersTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\NewslettersType' shared autowired service.
     *
     * @return \App\Form\NewslettersType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\NewslettersType'] = new \App\Form\NewslettersType();
    }
}
