<?php

namespace ContainerXm8YmtB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSiteInformationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SiteInformationRepository' shared autowired service.
     *
     * @return \App\Repository\SiteInformationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SiteInformationRepository'] = new \App\Repository\SiteInformationRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
