<?php

namespace ContainerXm8YmtB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendEmailControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SendEmailController' shared autowired service.
     *
     * @return \App\Controller\SendEmailController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SendEmailController'] = $instance = new \App\Controller\SendEmailController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\SendEmailController', $container));

        return $instance;
    }
}
