<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXm8YmtB\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXm8YmtB/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXm8YmtB.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXm8YmtB\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXm8YmtB\App_KernelProdContainer([
    'container.build_hash' => 'Xm8YmtB',
    'container.build_id' => '949b5f5a',
    'container.build_time' => 1715638515,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXm8YmtB');
