<?php

namespace ContainerGElN6Id;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XZxd7XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x_Zxd7X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x_Zxd7X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formBuilder' => ['privates', '.errored..service_locator.x_Zxd7X.Symfony\\Component\\Form\\FormBuilderInterface', NULL, 'Cannot autowire service ".service_locator.x_Zxd7X": it references interface "Symfony\\Component\\Form\\FormBuilderInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'formBuilder' => 'Symfony\\Component\\Form\\FormBuilderInterface',
        ]);
    }
}
