<?php

namespace ContainerDz1vXGS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hhm5ig8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hhm5ig8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hhm5ig8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'addressRepository' => ['privates', 'App\\Repository\\AddressRepository', 'getAddressRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'orders' => ['privates', '.errored..service_locator.hhm5ig8.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.hhm5ig8": it references class "App\\Entity\\Order" but no such service exists.'],
        ], [
            'addressRepository' => 'App\\Repository\\AddressRepository',
            'entityManagerInterface' => '?',
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'orders' => 'App\\Entity\\Order',
        ]);
    }
}
