<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXDsD5Gk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXDsD5Gk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXDsD5Gk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXDsD5Gk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXDsD5Gk\App_KernelDevDebugContainer([
    'container.build_hash' => 'XDsD5Gk',
    'container.build_id' => '9a90512e',
    'container.build_time' => 1716240599,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXDsD5Gk');
