<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGElN6Id\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGElN6Id/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGElN6Id.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGElN6Id\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGElN6Id\App_KernelDevDebugContainer([
    'container.build_hash' => 'GElN6Id',
    'container.build_id' => '9300061a',
    'container.build_time' => 1716238846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGElN6Id');
