<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'quantity', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'order_cost', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'order_cost_ttc', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'transporterName', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'transporterPrice', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'deliveryAddress', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'isPaid', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'method', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'orderDetails', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'tva'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'quantity', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'order_cost', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'order_cost_ttc', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'transporterName', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'transporterPrice', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'deliveryAddress', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'isPaid', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'method', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'orderDetails', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'tva'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderCost(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderCost', []);

        return parent::getOrderCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderCost(int $order_cost): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderCost', [$order_cost]);

        return parent::setOrderCost($order_cost);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', []);

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity(int $quantity): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', [$quantity]);

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderCostTtc(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderCostTtc', []);

        return parent::getOrderCostTtc();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderCostTtc(int $order_cost_ttc): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderCostTtc', [$order_cost_ttc]);

        return parent::setOrderCostTtc($order_cost_ttc);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransporterName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransporterName', []);

        return parent::getTransporterName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransporterName(string $transporterName): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransporterName', [$transporterName]);

        return parent::setTransporterName($transporterName);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransporterPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransporterPrice', []);

        return parent::getTransporterPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransporterPrice(float $transporterPrice): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransporterPrice', [$transporterPrice]);

        return parent::setTransporterPrice($transporterPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getdeliveryAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getdeliveryAddress', []);

        return parent::getdeliveryAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setdeliveryAddress(string $deliveryAddress): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setdeliveryAddress', [$deliveryAddress]);

        return parent::setdeliveryAddress($deliveryAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function isIsPaid(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsPaid', []);

        return parent::isIsPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPaid(bool $isPaid): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPaid', [$isPaid]);

        return parent::setIsPaid($isPaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMethod(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMethod', []);

        return parent::getMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setMethod(string $method): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMethod', [$method]);

        return parent::setMethod($method);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference(string $reference): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderDetails(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderDetails', []);

        return parent::getOrderDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderDetail(\App\Entity\OrderDetail $orderDetail): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderDetail', [$orderDetail]);

        return parent::addOrderDetail($orderDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderDetail(\App\Entity\OrderDetail $orderDetail): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderDetail', [$orderDetail]);

        return parent::removeOrderDetail($orderDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getTva(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTva', []);

        return parent::getTva();
    }

    /**
     * {@inheritDoc}
     */
    public function setTva(?int $tva): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTva', [$tva]);

        return parent::setTva($tva);
    }

}
