<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Payment extends \App\Entity\Payment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'imageUrl', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'test_public_api_key', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'test_private_api_key', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'prod_public_api_key', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'prod_private_api_key', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'createdAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'imageUrl', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'test_public_api_key', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'test_private_api_key', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'prod_public_api_key', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'prod_private_api_key', '' . "\0" . 'App\\Entity\\Payment' . "\0" . 'createdAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Payment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageUrl', []);

        return parent::getImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageUrl(?string $imageUrl): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageUrl', [$imageUrl]);

        return parent::setImageUrl($imageUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTestPublicApiKey(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTestPublicApiKey', []);

        return parent::getTestPublicApiKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setTestPublicApiKey(?string $test_public_api_key): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTestPublicApiKey', [$test_public_api_key]);

        return parent::setTestPublicApiKey($test_public_api_key);
    }

    /**
     * {@inheritDoc}
     */
    public function getTestPrivateApiKey(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTestPrivateApiKey', []);

        return parent::getTestPrivateApiKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setTestPrivateApiKey(?string $test_private_api_key): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTestPrivateApiKey', [$test_private_api_key]);

        return parent::setTestPrivateApiKey($test_private_api_key);
    }

    /**
     * {@inheritDoc}
     */
    public function getProdPublicApiKey(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProdPublicApiKey', []);

        return parent::getProdPublicApiKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setProdPublicApiKey(?string $prod_public_api_key): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProdPublicApiKey', [$prod_public_api_key]);

        return parent::setProdPublicApiKey($prod_public_api_key);
    }

    /**
     * {@inheritDoc}
     */
    public function getProdPrivateApiKey(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProdPrivateApiKey', []);

        return parent::getProdPrivateApiKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setProdPrivateApiKey(?string $prod_private_api_key): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProdPrivateApiKey', [$prod_private_api_key]);

        return parent::setProdPrivateApiKey($prod_private_api_key);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Payment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

}
